export const USER_POSTS_REQUEST = 'USER_POSTS_REQUEST'
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS'
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL'

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'
