export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const USER_GET_ALL_REQUEST = 'USER_GET_ALL_REQUEST'
export const USER_GET_ALL_SUCCESS = 'USER_GET_ALL_SUCCESS'
export const USER_GET_ALL_FAIL = 'USER_GET_ALL_FAIL'

export const USER_GET_SINGLE_REQUEST = 'USER_GET_SINGLE_REQUEST'
export const USER_GET_SINGLE_SUCCESS = 'USER_GET_SINGLE_SUCCESS'
export const USER_GET_SINGLE_FAIL = 'USER_GET_SINGLE_FAIL'
